CREATE DATABASE mercado_pascotto;

use mercado_pascotto;

create table produtos(
	id INT PRIMARY KEY,
    CODIGO_DE_BARRAS INT,
    NOME VARCHAR(255),
    MARCA VARCHAR(255),
    DATA_DE_VALIDADE DATE,
    FORNECEDOR VARCHAR(255),
    QUANTIDADE INT,
    PRECO_UNITARIO DECIMAL (10,2)    
);

create table FORNECEDORES(
	id INT PRIMARY KEY,
    CNPJ INT,
    NOME_DA_EMPRESA VARCHAR (255),
    ENDERECO VARCHAR(255),
    TELEFONE INT,
    EMAIL VARCHAR(255)    	
);

CREATE TABLE FUNCIONARIOS (
	id INT PRIMARY KEY,
    CPF INT,
    NOME VARCHAR (255),
    CARGO VARCHAR (255),
    EMIL VARCHAR(255),
    MATRICULA INT,
    TELEFONE INT,
    SALARIO DECIMAL(10,2)	
);
insert INTO PRODUTOS (ID, CODIGO_DE_BARRAS, NOME, MARCA, DATA_DE_VALIDADE,FORNECEDOR,QUANTIDADE,PRECO_UNITARIO) VALUES
(1, 1234, "CAFÉ", "NESCAFÉ", 20250420, "ATACADAO",1,30.99),
(2,4321,"LEITE","ITALAC",20250315,"ITALAC INDUSTRIES LTDA",10, 6.00);

UPDATE PRODUTOS
SET DATA_DE_VALIDADE = 20250315
where ID= 1;
UPDATE PRODUTOS
SET DATA_DE_VALIDADE = 20250420
where ID= 2;

SELECT*FROM FUNCIONÁRIOS